version: "3.8"
services:

  # Django Application
  app:
    container_name: duda_shop_django_app
    restart: always 
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 


